import {
  FIREBASE_API_KEY,
  FIREBASE_APP_ID,
  FIREBASE_PROJECT_ID,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_AUTH_DOMAIN,
} from '@env';

export type FirebaseEnv = {
  FIREBASE_API_KEY?: string;
  FIREBASE_APP_ID?: string;
  FIREBASE_PROJECT_ID?: string;
  FIREBASE_MESSAGING_SENDER_ID?: string;
  FIREBASE_STORAGE_BUCKET?: string;
  FIREBASE_AUTH_DOMAIN?: string;
};

export const firebaseEnv: FirebaseEnv = {
  FIREBASE_API_KEY,
  FIREBASE_APP_ID,
  FIREBASE_PROJECT_ID,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_AUTH_DOMAIN,
};

export const hasFirebaseConfig = (): boolean =>
  Boolean(FIREBASE_API_KEY && FIREBASE_APP_ID && FIREBASE_PROJECT_ID);